language: python
branches:
  only:  # safelist
    - master
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
install:
  - pip install flake8
  - pip install pytest
script:
  - pytest
  - head template.yaml
