language: python
branches:
  only:  # safelist
    - master
    - dev
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
install:
  - pip install flake8
  - pip install pytest
script:
  - flake8 --ignore=E501  # Lint Code
  - pytest                # Test Code
  - head template.yaml
